### ISSUE TITLE
Smarter building of feature dict/smarter feature replacement

### ISSUE THREAD

**Issue by ecsalomon** [dssg/triage#146]
Making a small change to a feature group (e.g., adding or removing a single feature) doesn't trigger replacing the feature table if replace is set to `False` and doesn't update the feature dict sent to the architect (dict is based on the table). 

This can be worked around by setting replace to `True`, but when there are several feature groups and only one has changed, it seems more desirable to simply update that one, especially when using leave-one-in and leave-one-out feature group combinations. In addition to feature table creation, many matrices and models could be skipped if the affect feature group is not included.

**Comment by thcrock** [comment]
@shaycrk and I were just talking about this, or at least a related issue. Basically, if instead of relying on the information schema to create the initial feature dict we get this by querying the collate Aggregation objects (could do something with the `get_columns` method of each contained Aggregate), we could enable a lot of things, including this. replace could be smarter in this case.

**Comment by thcrock** [comment]
Moved to https://github.com/dssg/architect/issues/14
