### ISSUE TITLE
Store worst possible version or metric

### ISSUE THREAD

**Issue by jesteria** [dssg/triage#292]
_From @thcrock on August 17, 2017 20:30_

Instead of ordering by score and then random, we want to calculate both label orderings, and take the worst one (based on the metric directionality).

_Copied from original issue: dssg/catwalk#12_

**Comment by thcrock** [comment]
After a lively discussion with many people, we have a plan for this: store worst/best/stochastic for each metric. I'll let somebody correct me, but I think the definition of 'stochastic' is "do it 30 times randomly and store the average".

**Comment by ecsalomon** [comment]
Definition of stochastic sounds right. We also want to store the standard deviation of the metric over the 30 trials.

If best & worst are the same, we can enter that value for stochastic and 0 for SD.

**Comment by thcrock** [comment]
Is there one of these (best/worst/stochastic) that we will designate as the default, for instance in audition? Do we force people to pick so that they know what they're getting into? Present 'worst' as the default because that's safest. or present 'stochastic' as the default because we do enough trials? @ecsalomon @saleiro

**Comment by thcrock** [comment]
Also, how should we deal with the existing column and its values? Copy it to the stochastic column, but indicate that only one trial was done?

**Comment by ecsalomon** [comment]
Rambling response: I am torn on the default question. We _could_ force people to choose one, or run audition on both stochastic and best (with, say, dashed/solid lines). Or perhaps use the `everyone at or above the delimiting score` (i.e., no tie-breaking) metric (which I realize is not part of this PR). I feel like stochastic is the most useful, but it makes sense to also look at the worst case and exclude some model group if their performance is highly variable depending on selection. Perhaps rather than running audition on the worst, we could store the variance (of the stochastic) or the range and include it as a filter parameter?

**Comment by thcrock** [comment]
Makes sense. So far I've added columns for # of trials and standard deviation. I could add the variance to this as well, no problem, if people think it's useful.

Based on your response and my own further thinking about it, using the stochastic version by default makes sense to me because with the migration behavior of copying the 1-run value over, this is just making it continue to do what it's doing now. Anything further can be considered an audition upgrade to do in a different PR, but that change would at least make this new functionality not break audition.

**Comment by ecsalomon** [comment]
Standard deviation is a transformation of variance -- no need for both. Agreed on pushing audition functionality changes to a new PR.

**Comment by thcrock** [comment]
Also, should we take the opportunity and make these columns less precise? There isn't necessarily a sizable enough storage gain here to make it worth it for that reason, but for database readability reasons and the fact that we're doing some value comparisons (e.g. if the best and worst are the same, skip all the stochastic processing) .

**Comment by ecsalomon** [comment]
Seems fine with me (would certainly save time for RFs and other learners that are extremely unlikely to produce ties). And certainly, I don't want audition to strongly recommend a model group with, like, 5th decimal place improvement over another model group. @rayidghani might have thoughts about _how_ precise the numbers should be.
