### ISSUE TITLE
Add Runs or batch table

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#440]
We need a way to store the state of the experiment and some other metadata related to the _execution_ of the experiment (e.g. who run it, from where, the final state of that run, the time, the cost(?), etc)

**Comment by ecsalomon** [comment]
Sometimes I want this information while a job is running, so it would be nice to create the row at the start of a run and update it as sections are completed.

**Comment by ecsalomon** [comment]
From long, long ago:

- start time
- end time
- n matrix jobs
- n matrices made
- n matrices skipped
- n modeling jobs
- n models trained
- n models skipped
- output of pip freeze
- current hash of the repo's head

From #147, which was migrated to catwalk and then migrated back as #289

**Comment by ecsalomon** [comment]
Is this only for .run()? Or for partial experiments?

**Comment by thcrock** [comment]
To follow up on the 'run' comment:

Instead of just 'run', we could create such a row whenever any method on the constructed experiment is invoked, and have that as a separate row. So if you do what many projects do and call 'generate_matrices' followed by 'train_and_test_models', you would have two rows:

generate_matrices would indicate that it created/skipped a bunch of matrices, but have blanks for models
train_and_test_models would have blanks/zeroes for matrix rows but indicate that it trained some # of models. 

Of course, if you called 'run', you would have just one row with all of that data.

**Comment by thcrock** [comment]
Progress at https://github.com/dssg/triage/compare/runs_table

Yet to be decided: How to handle distributed execution? For instance, although the parent process knows how many matrices it needs to build, it doesn't really see them getting built. Should the child processes specifically pass this data back to the parent process and have it update the row? Or should we have each process that finishes a matrix increment the row's value in the DB and deal with race conditions there?

**Comment by thcrock** [comment]
- OS user
- working directory
- instance type
- log location if root handler has a filehandler
- runtime experiment kwargs (as a json blob, censor the db engine)

**Comment by thcrock** [comment]
Perhaps matrices and models also need an 'errored' counter. We won't necessarily catch all of the possible errors (e.g. process getting killed by the OS), but we can catch some and being able to see if the counts don't add up will make it easier to see if anything really wonky went on. 

We also talked about a stacktrace exception. This, for the same reason as above, isn't always available but allowing it to sometimes be available will be helpful for when the reason for dying is something other than memory. Also, for the same reason above its absence is itself useful data.
