### ISSUE TITLE
Make INFO level logging less spammy

### ISSUE THREAD

**Issue by thcrock** [dssg/triage#596]
INFO level logging, which is usually watched by experimenters while the experiment is going, has too many messages to really see progress. It's useful data of course, but it'd be nice to log progress in an easier to see manner.

Proposal:
- Most of the current log messages get moved to DEBUG
- The INFO level would be limited to messages like "Matrix 4 of 42 built" (have counts for each phase like cohort/label/etc)
- The CLI defaults to INFO level to stdout, DEBUG level to a file within the ProjectStorage

This still allows people with their own run.py to configure DEBUG logging to whatever they want.  I'm not sure how this would work with AWS batch, but potentially if the Batch runner's run.py included both INFO and DEBUG in the log stream that gets sent to Cloudwatch, they could now switch filtering between INFO-level and DEBUG-level depending on the view they wanted to see at the time. (pinging @nanounanue )

**Comment by nanounanue** [comment]
We could use a config file

The main problem is the logging of `boto3` (at least if you are using `s3`)

**Comment by thcrock** [comment]
I'm not sure what you are referring to with the config file. Can you elaborate?

**Comment by nanounanue** [comment]
https://stackoverflow.com/questions/4441842/python-logging-configuration-file

We can just include one in the module

**Comment by jesteria** [comment]
Yes, you can configure `logging` via config file or in-Python `dict`. I think @nanounanue is asking how we'd like people to override defaults, in AWS Batch or otherwise.

I'm guessing it's fine to leave this to the user -- if they have a `run.py` or what-have-you, they can do it there. I suppose users of the CLI can use the setup file at `experiment.py`.

@nanounanue would that be sufficient? Or do we also need/want Triage to look for some default logging configuration file?

---

As for boto3, @nanounanue, I've had the same problem. It's a separate issue, and not one that I think Triage would necessarily want to "fix"; but, it has the same resolution -- redirect or kill boto3's debug logs, via the logging config for your experiment.

**Comment by thcrock** [comment]
I wouldn't be opposed to helpfully killing the boto barf for CLI users. I think CLI users should get a reasonable default, and I don't think keeping in those boto DEBUGs counts as a reasonable default. It could make sense to accomplish this by providing it in an example shipped setup file, as opposed to hardcoding it in CLI.py.

**Comment by nanounanue** [comment]
@jesteria I am totally agree with you. 

@thcrock I am not following you (probably because I am feeling well) but the problem with `boto` is not related to the `cli` exclusively.

**Comment by jesteria** [comment]
Cool, it sounds like for Triage logging _configuration_, we're already set -- users can configure this however they like, via their Python, (regardless of whether they're using the CLI, since they have that CLI setup module).

For the sub-issue of boto's default configuration, I'm not sure we want to get involved by default, and users can always tweak this (as above). But, if it's a serious issue … yes, there are lots of ways to tweak it.

I think we've established though that all of this is separate from the main problem targeted by this Issue -- that Triage is over-reliant on the `INFO` log level. Work towards this Issue can remedy that.

(If there's anything to do about boto, that should probably be a separate Issue?)
