### ISSUE TITLE
stamp_db not up to date with experiment config version

### ISSUE THREAD

**Issue by ecsalomon** [dssg/triage#697]
https://github.com/dssg/triage/blob/master/src/triage/component/results_schema/__init__.py#L77

`stamp_db` only knows config versions through `v5`, but we are now on `v7`. 

The experiment versioning section of the contributing guide should also mention making changes to `stamp_db`.

**Comment by thcrock** [comment]
I propose that we instead make `stamp_db` wrap the alembic version more directly, using schema revisions rather than experiment config versions (which don't necessarily map to one unique schema revision). The code that you are referring to was kind of a backfill bridge from the pre-alembic era to the alembic era. 

Examples:

`triage db stamp head` would stamp the db to whatever the code's most recent schema revision is (this is almost always what people would want to use it for).
`triage db stamp 97cf99b7348f` would stamp the db to that particular revision.

**Comment by thcrock** [comment]
Note: If you want to do this right now without waiting for a code change, just use the management command in Triage:

`manage alembic stamp head`
