### ISSUE TITLE
duplicate models with the same random seed

### ISSUE THREAD

**Issue by shaycrk** [dssg/triage#732]
The recent changes to allow for different models to be created with the same parameters but different random seeds seems like it might have eliminated a uniqueness constraint somewhere and we've been seeing cases where we end up with duplicate records in `model_metadata.models` (including the same random seed) but different `model_id` values.

**Comment by nanounanue** [comment]
Could you share an snippet of your config file? So I can try to duplicate this?

**Comment by shaycrk** [comment]
@nanounanue -- I believe we saw this initially with @hemanklamba and @KasunAmare running some models on the donors choose data, but have encountered it with the Chapin Hall child welfare model runs as well. 

I don't particularly have a minimal working example handy, but think we should see it with any re-run of the same model (including the same random seed), though am less sure on how it interacts with the replace flag... Might be good to try out with something like a single random forest on dirty duck?

**Comment by nanounanue** [comment]
Good idea @adunmore  also provide with some examples. Thank you!

**Comment by KasunAmare** [comment]
@nanounanue please scratch what I said in the meeting today about models not being duplicated on disk.

I went through our past donors-choose runs.  I'm not sure whether I'm saying something redundant, but this is what I found. 

Saw that triage allows re-running the same experiment (with the same hash) even if it was completed. Is triage supposed to do that? 

The model duplication we were seeing for the same `built_by_experiment` and `model_group_id` was because the experiment ran twice. The models have different ids and hashes.  My understanding was that triage wouldn't re-train and save models. 

If this is the expected behavior, we may not have a model duplication error? and if it is the case, should we use experiment_hash and something else (`model_building_time`?) as the unique identifier of a run? 

The experiment I checked had 7 timechop splits. These are the queries I used to check the above. 

`select * from model_metadata.experiment_runs where experiment_hash='0f0abbf0d62a61706253f2ec9769273c' and current_status='completed' order by start_time;`

`select * from model_metadata.models where built_by_experiment='0f0abbf0d62a61706253f2ec9769273c' and model_group_id=496;`

**Comment by thcrock** [comment]
I may be able to help a little bit:

"Saw that triage allows re-running the same experiment (with the same hash) even if it was completed. Is triage supposed to do that?"

Triage hasn't as of yet been designed to *disallow* running the same experiment twice. If the replace flag is True, it would truly re-do all the work (with all of the same hashes). If it's False, it would essentially no-op on the second run (not retrain anything). Random seeds could changes this. However, since the entire experiment config is hashed to make the experiment hash, and the experiment random seed is part of the experiment config, a changed *experiment* random seed  should make it a new experiment IIRC.

"The model duplication we were seeing for the same built_by_experiment and model_group_id was because the experiment ran twice. The models have different ids and hashes. My understanding was that triage wouldn't re-train and save models."

If replace is false, this statement makes sense. The scenario in which the same model group gets a new model is if the model's random seed has changed. I don't recall exactly how the *model* random seed is created, as this was created very recently (in terms of active Triage development) and not tested a ton. But this is what I'd dig into; check out `src/triage/component/catwalk/model_trainers.py, line 244 _train_and_store_model` to see where the model random seed gets used.

**Comment by ecsalomon** [comment]
To add a little to @thcrock's first answer: This is largely supported to allow re-running an experiment on new/revised data (e.g., after fixing a bug in a cleaning script).

**Comment by thcrock** [comment]
Addendum to my model random seed comment:
The model random seed is generated when the training task is created. So a useful thing to figure out is whether or not the model random seeds are changing.  It looks like this model random seed is stored in the models table, in the record's misc db parameters.

**Comment by nanounanue** [comment]
@thcrock yes, I am exactly working on that. Thanks for your comments
