### ISSUE TITLE
Broken dependency graphs in Triage architecture docs

### ISSUE THREAD

**Issue by adunmore** [dssg/triage#765]
The dependency graphs at [dssg.github.io/triage/experiments/architecture/](dssg.github.io/triage/experiments/architecture/) aren't rendering.

**Comment by thcrock** [comment]
This confused me too (I was trying to show the graphs to somebody). mermaid js is bundled in the repository so that hasn't updated, and it appears that mkdocs hasn't been updated since mermaid was introduced. 

The console error looks interesting though:

"Error: Lexical error on line 15. Unrecognized text.
...tor]    end    TC → LG    TC → EDG  
---------------------^"

Those arrows are not what is in the code!

    TC --> LG
    TC --> EDG
    TC --> FG

Is one of the new markdown extensions converting the latter to the former and breaking it?
