### ISSUE TITLE
Modularize Collate Generation Step

### ISSUE THREAD

**Issue by ecsalomon** [dssg/triage#80]
Allow a user to output a list of all the collate objects that would be created from the yaml. This would be useful for debugging and improving queries.

**Comment by thcrock** [comment]
So skipping straight to the collate part is certainly possible right now for debugging purposes: a user can, instead of instantiating a Pipeline subclass, instantiate a FeatureGenerator and call it directly. Something like this:

from triage.features import FeatureGenerator
fg = FeatureGenerator(db_engine=..., features_schema_name=...)

To immediately run this (to see SQL errors):
fg.generate(feature_aggregations=experiment_config['feature_aggregations'], feature_dates=...)

To just get all the Aggregation objects returned to you for your own inspection, lifting the first few lines from `generate`:
https://github.com/dssg/triage/blob/master/triage/feature_generators.py#L59

```        aggregations = [
            fg.aggregation(aggregation_config, feature_dates=...)
            for aggregation_config in experiment_config['feature_aggregations']
]```

This does miss one part: calling it in context with the final as_of_dates from your config. This clearly requires running the Chopper, though this can also be done without too much trouble. But if you're just trying to figure out if your queries are reasonable, the above should work for now.

**Comment by thcrock** [comment]
Pipeline now has `feature_table_tasks` and `feature_dicts` methods as part of a restructuring:

https://github.com/dssg/triage/blob/master/triage/pipelines/base.py#L205
